### ISSUE TITLE
编译成功，但是运行失败

### ISSUE THREAD

**Issue by kissthink** [scarsty/kys-pig3#1]
使用了lazarus 1.6进行编译，编译成功，运行失败，提示缺失各种dll。
手动安装了这些库external libraries are SDL/SDL-ttf/SDL-image, BASS, ffmpeg, Lua之后，还是不能运行，最后提示一个内存访问非法错误。能详细说明下安装的额外库的版本，和下载地址么？谢谢

**Comment by scarsty** [comment]
什么系统

**Comment by kissthink** [comment]
是在xp下编译运行的

**Comment by godka** [comment]
1.把缺少的dll复制到编译完毕的exe同目录下
2.如果已经完成1，请把dll和exe放在游戏目录包下
3.如果还出现错误，请报告错误代码以及错误信息。

**Comment by scarsty** [comment]
你可能是没有完整游戏，到 dawuxia.net 找下载。
